#!/usr/bin/env bash
set -e
SELF=${BASH_SOURCE[0]}

if LINKSELF=$(readlink "$SELF"); then
  SELF="$LINKSELF"
fi

DIR="$(cd "$(dirname "$SELF")" && pwd)"
LINKED="$DIR/.linked"

CMD="$1"

case "$CMD" in
  link)
    if [ $# -lt 2 ]; then
      echo "Usage: $0 link NAME [TARGET]"
      exit 1
    fi

    source_path="$DIR/$2"

    if [ $# -eq 2 ]; then
      target=".$2"
    else
      target="$3"
    fi
    target_path="$HOME/$target"

    if [ -e "$target_path" ]; then
      echo "$target_path already exists. Aborting."
      exit 2
    fi

    if [ ! -e "$source_path" ]; then
      echo "$source_path doesn't exists. Aborting."
      exit 2
    fi

    ln -s "$source_path" "$target_path"
    echo "$target" >> "$LINKED"
    ;;
  linked)
    cat "$LINKED" 2>/dev/null
    ;;
  rm)
    if [ $# -lt 2 ]; then
      echo "Usage: $0 rm TARGET"
      exit 1
    fi

    cat "$LINKED" | grep -Fxv "$2" > "$LINKED.new"
    if cmp --silent "$LINKED" "$LINKED.new"; then
      echo "$2 was not linked with dotfile manager. Aborting."
      rm "$LINKED.new"
      exit 2
    fi

    rm -f "$HOME/$2"
    mv "$LINKED.new" "$LINKED"
    ;;
  ls)
    ls -1 "$DIR" | grep -Fxv manager
    ;;
  *)
    echo "Usage: $0 {link|linked|ls|rm}"
  ;;
esac
